name: Update GitHub Profile README

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 0 点运行
  workflow_dispatch:      # 允许手动触发
  push:
    branches: [ "master" ]  # 当推送到 master 分支时触发

jobs:
  update-readme:
    name: Update Profile README
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      # 更新 Profile 访问计数
      - name: Profile Views Counter
        uses: antonkomarev/github-profile-views-counter@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          username: lhui

      # 生成 Metrics
      - name: Generate Metrics
        uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: lhui
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Shanghai
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_threshold: C
          plugin_habits: yes
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_stars: yes
          plugin_stars_limit: 4
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: icons
          plugin_people: yes
          plugin_people_limit: 28
          plugin_people_size: 28
          plugin_people_types: followers, following
          plugin_notable: yes
          plugin_discussions: yes
          plugin_support: yes

      # 生成 GitHub 统计信息
      - name: GitHub Stats Card
        uses: anuraghazra/github-readme-stats@master
        with:
          username: lhui
          show_icons: true
          count_private: true
          theme: radical
          hide_border: true
          cache_seconds: 1800
          include_all_commits: true
          
      # 生成编程语言统计
      - name: Top Languages Card
        uses: anuraghazra/github-readme-stats@master
        with:
          username: lhui
          layout: compact
          theme: radical
          hide_border: true
          langs_count: 10
          
      # 生成贡献图表动画
      - name: Generate Snake Animation
        uses: Platane/snk@master
        with:
          github_user_name: lhui
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
            
      # 生成 GitHub Trophy
      - name: GitHub Trophy
        uses: ryo-ma/github-profile-trophy@master
        with:
          username: lhui
          theme: radical
          
      # 提交更改
      - name: Commit and Push
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A .
          git commit -m "docs(readme): 更新 Profile 统计信息 $(date +'%Y-%m-%d')" || exit 0
          git push