name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *" # 每12小时运行一次
  workflow_dispatch:
  push:
    branches: [ "main", "master" ]

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      # 创建 dist 目录
      - name: Create dist directory
        run: mkdir -p dist

      - name: Generate Snake Animation
        uses: Platane/snk@master
        with:
          github_user_name: lhui
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # 确保文件存在后再提交
      - name: Push to GitHub
        run: |
          cd dist
          if [ -f "github-contribution-grid-snake.svg" ] && [ -f "github-contribution-grid-snake-dark.svg" ]; then
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add .
            git commit -m "Generate Snake Animation"
            git push
          else
            echo "Snake animation files were not generated"
            exit 1
          fi