name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Generate Snake Animation
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: lhui
          svg_out_path: dist/github-contribution-grid-snake.svg
          dark_svg_out_path: dist/github-contribution-grid-snake-dark.svg

      - name: Debug directory contents
        run: |
          ls -la
          ls -la dist || echo "dist directory not found"

      - name: Push Changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add dist/
          git commit -m "Generate Snake Animation" || echo "No changes to commit"
          git push origin HEAD