name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *" # 每12小时运行一次
  workflow_dispatch:
  push:
    branches: [ "master" ]

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      
      - name: Generate Snake Animation
        uses: Platane/snk@master
        with:
          github_user_name: lhui
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            
      - name: Push to GitHub
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add dist/
          git commit -m "Generate Snake Animation" || exit 0
          git push